version: "3.7"
services:
  morphicweb:
    build:
      context: .
    ports:
      - "80:80"
    environment:
      SERVICE_URL:    "http://localhost:5002/"
      RECAPTCHA_KEY:  "6Le6hfsUAAAAAB9-WagMKxjnZmP7RKrSxlTYjJc-"

