version: "3.7"
services:
  morphicweb:
    build:
      context: .
    ports:
      - "5003:80"
    environment:
      SERVICE_URL:    "${SERVICE_URL:-http://localhost:5002/}"
      RECAPTCHA_KEY:  "${RECAPTCHA_KEY:-6Lc1hfsUAAAAAGFReCJUUva4LHF30XG5pIoJr2Nl}"
    volumes:
    - type: bind
      source: ./www
      target: /MorphicLiteWeb/www

